# Generated by Django 4.2.4 on 2023-08-24 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='body',
            field=models.TextField(max_length=500),
        ),
    ]
